<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260927020255 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE addresses (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', client_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', street1 VARCHAR(255) DEFAULT NULL, street2 VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, state VARCHAR(255) DEFAULT NULL, zip VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_6FCA751619EB6921 (client_id), INDEX IDX_6FCA7516979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE api_token_history (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', token_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', ip VARCHAR(255) NOT NULL, resource VARCHAR(125) NOT NULL, method VARCHAR(25) NOT NULL, requestData LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', userAgent VARCHAR(255) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_61D8DC4441DEE7B9 (token_id), INDEX IDX_61D8DC44979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE api_tokens (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', user_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', name VARCHAR(125) NOT NULL, token VARCHAR(125) NOT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_2CAD560EA76ED395 (user_id), INDEX IDX_2CAD560E979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE app_config (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', setting_key VARCHAR(125) NOT NULL, setting_value LONGTEXT DEFAULT NULL, description LONGTEXT DEFAULT NULL, field_type VARCHAR(255) NOT NULL, form_options JSON DEFAULT NULL, default_value LONGTEXT DEFAULT NULL, INDEX IDX_318942FC979B1AD6 (company_id), UNIQUE INDEX UNIQ_318942FC5FA1E697979B1AD6 (setting_key, company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client_credit (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', client_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', value_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', created DATETIME NOT NULL, updated DATETIME NOT NULL, UNIQUE INDEX UNIQ_4967254D19EB6921 (client_id), INDEX IDX_4967254D979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE clients (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', name VARCHAR(125) NOT NULL, website VARCHAR(125) DEFAULT NULL, status VARCHAR(25) NOT NULL, currency VARCHAR(3) DEFAULT NULL, archived TINYINT(1) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_C82E74979B1AD6 (company_id), UNIQUE INDEX UNIQ_C82E745E237E06979B1AD6 (name, company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE companies (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', name VARCHAR(255) NOT NULL, custom_domain VARCHAR(253) DEFAULT NULL, UNIQUE INDEX UNIQ_8244AA3A9304CA0F (custom_domain), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contacts (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', client_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', firstName VARCHAR(125) NOT NULL, lastName VARCHAR(125) DEFAULT NULL, email VARCHAR(255) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_3340157319EB6921 (client_id), INDEX IDX_33401573979B1AD6 (company_id), INDEX IDX_33401573E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE custom_field (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', target VARCHAR(32) NOT NULL, label VARCHAR(125) NOT NULL, field_key VARCHAR(64) NOT NULL, type VARCHAR(32) NOT NULL, options JSON DEFAULT NULL, default_value LONGTEXT DEFAULT NULL, visibility VARCHAR(32) DEFAULT NULL, required TINYINT(1) DEFAULT 0 NOT NULL, position INT DEFAULT 0 NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_98F8BD31979B1AD6 (company_id), INDEX idx_cf_company_target_pos (company_id, target, position), UNIQUE INDEX uq_cf_company_target_key (company_id, target, field_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE custom_field_value (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', field_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', target VARCHAR(32) NOT NULL, target_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', value LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_EC7B05979B1AD6 (company_id), INDEX idx_cfv_company_target_record (company_id, target, target_id), INDEX idx_cfv_field (field_id), UNIQUE INDEX uq_cfv_field_record (field_id, target_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE export_jobs (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', status VARCHAR(20) NOT NULL, archive_path VARCHAR(512) DEFAULT NULL, file_size INT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', completed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', failure_reason LONGTEXT DEFAULT NULL, requested_by BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', format VARCHAR(10) NOT NULL, INDEX IDX_8E225B2E979B1AD6 (company_id), INDEX IDX_8E225B2E18C491A5 (requested_by), INDEX IDX_8E225B2E7B00651C (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE invoice_lines (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', invoice_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', description LONGTEXT NOT NULL, price_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', qty DOUBLE PRECISION NOT NULL, total_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', created DATETIME NOT NULL, updated DATETIME NOT NULL, type VARCHAR(255) NOT NULL, recurringInvoice_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', INDEX IDX_72DBDC232989F1FD (invoice_id), INDEX IDX_72DBDC23979B1AD6 (company_id), INDEX IDX_72DBDC23416CCF0F (recurringInvoice_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE invoice_reminders (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', invoice_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', reminder_type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, sent_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', failure_reason LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_83D48482989F1FD (invoice_id), INDEX IDX_83D4848979B1AD6 (company_id), UNIQUE INDEX UNIQ_83D4848979B1AD62989F1FD9B228B00 (company_id, invoice_id, reminder_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE invoice_tax (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', tax_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', invoice_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', quote_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', recurring_invoice_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', direction VARCHAR(32) DEFAULT \'Additive\' NOT NULL, name_snapshot VARCHAR(32) NOT NULL, rate_snapshot NUMERIC(10, 4) NOT NULL, category_snapshot VARCHAR(32) DEFAULT \'Standard\' NOT NULL, type_snapshot VARCHAR(32) DEFAULT \'Exclusive\' NOT NULL, amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', note LONGTEXT DEFAULT NULL, sequence SMALLINT DEFAULT 0 NOT NULL, snapshotted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_2670D5B5B2A824D8 (tax_id), INDEX IDX_2670D5B52989F1FD (invoice_id), INDEX IDX_2670D5B5DB805178 (quote_id), INDEX IDX_2670D5B59F85F85C (recurring_invoice_id), INDEX IDX_2670D5B5979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE invoices (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', client_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', quote_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', recurring_invoice_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', total_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', baseTotal_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', tax_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', terms LONGTEXT DEFAULT NULL, notes LONGTEXT DEFAULT NULL, withholding_amount BIGINT DEFAULT \'0\' NOT NULL COMMENT \'(DC2Type:BigInteger)\', payable_amount BIGINT DEFAULT \'0\' NOT NULL COMMENT \'(DC2Type:BigInteger)\', status VARCHAR(25) NOT NULL, invoice_id VARCHAR(255) NOT NULL, uuid VARCHAR(36) NOT NULL, balance_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', due DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', invoice_date DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', paid_date DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', archived TINYINT(1) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, discount_valueMoney_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', discount_value_percentage DOUBLE PRECISION DEFAULT NULL, discount_type VARCHAR(255) DEFAULT NULL, INDEX IDX_6A2F2F95979B1AD6 (company_id), INDEX IDX_6A2F2F9519EB6921 (client_id), UNIQUE INDEX UNIQ_6A2F2F95DB805178 (quote_id), INDEX IDX_6A2F2F959F85F85C (recurring_invoice_id), INDEX IDX_6A2F2F95DB805178 (quote_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE invoice_contact (invoice_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', contact_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', INDEX IDX_BEBBD0EB2989F1FD (invoice_id), INDEX IDX_BEBBD0EBE7A1254A (contact_id), PRIMARY KEY(invoice_id, contact_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE line_tax (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', tax_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', invoice_line_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', quote_line_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', name_snapshot VARCHAR(32) NOT NULL, rate_snapshot NUMERIC(10, 4) NOT NULL, category_snapshot VARCHAR(32) DEFAULT \'Standard\' NOT NULL, type_snapshot VARCHAR(32) NOT NULL, compound TINYINT(1) DEFAULT 0 NOT NULL, sequence SMALLINT DEFAULT 0 NOT NULL, amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', snapshotted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_7DCA892CB2A824D8 (tax_id), INDEX IDX_7DCA892CBFA24391 (invoice_line_id), INDEX IDX_7DCA892CA294DDC6 (quote_line_id), INDEX IDX_7DCA892C979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mcp_access_token (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', client_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', jti VARCHAR(128) NOT NULL, scope_values JSON NOT NULL, expires_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', revoked TINYINT(1) NOT NULL, last_used_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created DATETIME NOT NULL, updated DATETIME NOT NULL, UNIQUE INDEX UNIQ_8611E117C53CF2EA (jti), INDEX IDX_8611E11719EB6921 (client_id), INDEX IDX_8611E117A76ED395 (user_id), INDEX IDX_8611E117979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mcp_consent_grant (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', client_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', scopes JSON NOT NULL, remember_consent TINYINT(1) DEFAULT 0 NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_90F67619EB6921 (client_id), INDEX IDX_90F676A76ED395 (user_id), INDEX IDX_90F676979B1AD6 (company_id), UNIQUE INDEX uniq_consent_grant (client_id, user_id, company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mcp_oauth_auth_code (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', client_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', identifier VARCHAR(128) NOT NULL, scope_values JSON NOT NULL, redirect_uri VARCHAR(2048) DEFAULT NULL, expires_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', revoked TINYINT(1) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, UNIQUE INDEX UNIQ_33244474772E836A (identifier), INDEX IDX_3324447419EB6921 (client_id), INDEX IDX_33244474A76ED395 (user_id), INDEX IDX_33244474979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mcp_oauth_client (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', created_by_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', name VARCHAR(255) NOT NULL, redirect_uris JSON NOT NULL, grant_types JSON NOT NULL, scopes JSON NOT NULL, secret_hash VARCHAR(255) DEFAULT NULL, token_endpoint_auth_method VARCHAR(32) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_9DC01B32B03A8386 (created_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mcp_refresh_token (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', access_token_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', identifier VARCHAR(128) NOT NULL, expires_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', revoked TINYINT(1) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, UNIQUE INDEX UNIQ_7C5FE04772E836A (identifier), INDEX IDX_7C5FE042CCB2688 (access_token_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification_transport_setting (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', user_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', name VARCHAR(255) NOT NULL, transport VARCHAR(255) NOT NULL, settings JSON NOT NULL, INDEX IDX_C825F288A76ED395 (user_id), INDEX IDX_C825F288979B1AD6 (company_id), UNIQUE INDEX unique_name_user (name, company_id, user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification_user_setting (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', user_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', event VARCHAR(255) NOT NULL, email TINYINT(1) NOT NULL, INDEX IDX_C6774CA7A76ED395 (user_id), INDEX IDX_C6774CA7979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE usernotification_transportsetting (usernotification_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', transportsetting_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', INDEX IDX_F4035D6F58E61F52 (usernotification_id), INDEX IDX_F4035D6F356A9AF4 (transportsetting_id), PRIMARY KEY(usernotification_id, transportsetting_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment_methods (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', name VARCHAR(125) NOT NULL, gateway_name VARCHAR(125) NOT NULL, factory VARCHAR(125) NOT NULL, config LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', internal TINYINT(1) DEFAULT NULL, enabled TINYINT(1) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_4FABF983979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payments (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', invoice_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', client BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', method_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', number VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, client_email VARCHAR(255) DEFAULT NULL, client_id VARCHAR(255) DEFAULT NULL, total_amount INT DEFAULT NULL, currency_code VARCHAR(255) DEFAULT NULL, details JSON NOT NULL, status VARCHAR(25) NOT NULL, message LONGTEXT DEFAULT NULL, completed DATETIME DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL, notes LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_65D29B322989F1FD (invoice_id), INDEX IDX_65D29B32C7440455 (client), INDEX IDX_65D29B3219883967 (method_id), INDEX IDX_65D29B32979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE quote_lines (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', quote_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', description LONGTEXT NOT NULL, price_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', qty DOUBLE PRECISION NOT NULL, total_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_42FE01F7DB805178 (quote_id), INDEX IDX_42FE01F7979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE quotes (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', client_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', quote_id VARCHAR(255) NOT NULL, uuid VARCHAR(36) NOT NULL, status VARCHAR(25) NOT NULL, total_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', baseTotal_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', tax_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', withholding_amount BIGINT DEFAULT \'0\' NOT NULL COMMENT \'(DC2Type:BigInteger)\', payable_amount BIGINT DEFAULT \'0\' NOT NULL COMMENT \'(DC2Type:BigInteger)\', terms LONGTEXT DEFAULT NULL, notes LONGTEXT DEFAULT NULL, due DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', archived TINYINT(1) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, discount_valueMoney_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', discount_value_percentage DOUBLE PRECISION DEFAULT NULL, discount_type VARCHAR(255) DEFAULT NULL, INDEX IDX_A1B588C519EB6921 (client_id), INDEX IDX_A1B588C5979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE quote_contact (quote_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', contact_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', INDEX IDX_A38D4EBCDB805178 (quote_id), INDEX IDX_A38D4EBCE7A1254A (contact_id), PRIMARY KEY(quote_id, contact_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE recurring_invoices (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', client_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', total_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', baseTotal_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', tax_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', terms LONGTEXT DEFAULT NULL, notes LONGTEXT DEFAULT NULL, withholding_amount BIGINT DEFAULT \'0\' NOT NULL COMMENT \'(DC2Type:BigInteger)\', payable_amount BIGINT DEFAULT \'0\' NOT NULL COMMENT \'(DC2Type:BigInteger)\', status VARCHAR(25) NOT NULL, date_start DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', date_end DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', archived TINYINT(1) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, discount_valueMoney_amount BIGINT NOT NULL COMMENT \'(DC2Type:BigInteger)\', discount_value_percentage DOUBLE PRECISION DEFAULT NULL, discount_type VARCHAR(255) DEFAULT NULL, INDEX IDX_FE93E284979B1AD6 (company_id), INDEX IDX_FE93E28419EB6921 (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE recurringinvoice_contacts (recurringinvoice_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', contact_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', INDEX IDX_DA79A131E31CCDF (recurringinvoice_id), INDEX IDX_DA79A131E7A1254A (contact_id), PRIMARY KEY(recurringinvoice_id, contact_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE recurring_options (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', type VARCHAR(15) NOT NULL, days JSON NOT NULL, endType VARCHAR(15) NOT NULL, endDate DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', endOccurrence INT DEFAULT NULL, recurringInvoice_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', UNIQUE INDEX UNIQ_8C36F0E416CCF0F (recurringInvoice_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reset_password_request (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', selector VARCHAR(20) NOT NULL, hashedToken VARCHAR(100) NOT NULL, requestedAt DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', expiresAt DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_7CE748AA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE security_token (hash VARCHAR(255) NOT NULL, payment_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', details LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:object)\', after_url LONGTEXT DEFAULT NULL, target_url LONGTEXT NOT NULL, gateway_name VARCHAR(255) NOT NULL, INDEX IDX_B38B42914C3A3BB (payment_id), PRIMARY KEY(hash)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tax_identifier (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', client_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', label VARCHAR(32) NOT NULL, value VARCHAR(64) NOT NULL, is_primary TINYINT(1) DEFAULT 0 NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_ACB973B619EB6921 (client_id), INDEX IDX_ACB973B6979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tax_rates (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', name VARCHAR(32) NOT NULL, rate DOUBLE PRECISION NOT NULL, tax_type VARCHAR(32) NOT NULL, category VARCHAR(32) DEFAULT \'Standard\' NOT NULL, compound TINYINT(1) DEFAULT 0 NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_F7AE5E1D979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_invitations (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', invited_by_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', email VARCHAR(255) NOT NULL, created DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz_immutable)\', expiresAt DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz_immutable)\', reminderSentAt DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz_immutable)\', status VARCHAR(255) NOT NULL, INDEX IDX_8A3CD93BA7B4A7E3 (invited_by_id), INDEX IDX_8A3CD93B979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_settings (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', setting_key VARCHAR(125) NOT NULL, setting_value LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_5C844C5A76ED395 (user_id), UNIQUE INDEX UNIQ_5C844C55FA1E697A76ED395 (setting_key, user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', created DATETIME NOT NULL, updated DATETIME NOT NULL, totp_secret VARCHAR(45) DEFAULT NULL, auth_code VARCHAR(45) DEFAULT NULL, email_auth_enabled TINYINT(1) DEFAULT NULL, trusted_version INT DEFAULT 0 NOT NULL, backup_codes JSON DEFAULT NULL, first_name VARCHAR(45) DEFAULT NULL, last_name VARCHAR(45) DEFAULT NULL, mobile VARCHAR(255) DEFAULT NULL, email VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, verified TINYINT(1) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', google_id VARCHAR(45) DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_company (user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', company_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', INDEX IDX_17B21745A76ED395 (user_id), INDEX IDX_17B21745979B1AD6 (company_id), PRIMARY KEY(user_id, company_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE version (version VARCHAR(125) NOT NULL, PRIMARY KEY(version)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE addresses ADD CONSTRAINT FK_6FCA751619EB6921 FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE addresses ADD CONSTRAINT FK_6FCA7516979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE api_token_history ADD CONSTRAINT FK_61D8DC4441DEE7B9 FOREIGN KEY (token_id) REFERENCES api_tokens (id)');
        $this->addSql('ALTER TABLE api_token_history ADD CONSTRAINT FK_61D8DC44979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE api_tokens ADD CONSTRAINT FK_2CAD560EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE api_tokens ADD CONSTRAINT FK_2CAD560E979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE app_config ADD CONSTRAINT FK_318942FC979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE client_credit ADD CONSTRAINT FK_4967254D19EB6921 FOREIGN KEY (client_id) REFERENCES clients (id)');
        $this->addSql('ALTER TABLE client_credit ADD CONSTRAINT FK_4967254D979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE clients ADD CONSTRAINT FK_C82E74979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contacts ADD CONSTRAINT FK_3340157319EB6921 FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contacts ADD CONSTRAINT FK_33401573979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE custom_field ADD CONSTRAINT FK_98F8BD31979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE custom_field_value ADD CONSTRAINT FK_EC7B05443707B0 FOREIGN KEY (field_id) REFERENCES custom_field (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE custom_field_value ADD CONSTRAINT FK_EC7B05979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE export_jobs ADD CONSTRAINT FK_8E225B2E979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice_lines ADD CONSTRAINT FK_72DBDC232989F1FD FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice_lines ADD CONSTRAINT FK_72DBDC23979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice_lines ADD CONSTRAINT FK_72DBDC23416CCF0F FOREIGN KEY (recurringInvoice_id) REFERENCES recurring_invoices (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice_reminders ADD CONSTRAINT FK_83D48482989F1FD FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice_reminders ADD CONSTRAINT FK_83D4848979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice_tax ADD CONSTRAINT FK_2670D5B5B2A824D8 FOREIGN KEY (tax_id) REFERENCES tax_rates (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE invoice_tax ADD CONSTRAINT FK_2670D5B52989F1FD FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice_tax ADD CONSTRAINT FK_2670D5B5DB805178 FOREIGN KEY (quote_id) REFERENCES quotes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice_tax ADD CONSTRAINT FK_2670D5B59F85F85C FOREIGN KEY (recurring_invoice_id) REFERENCES recurring_invoices (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice_tax ADD CONSTRAINT FK_2670D5B5979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoices ADD CONSTRAINT FK_6A2F2F95979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoices ADD CONSTRAINT FK_6A2F2F9519EB6921 FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoices ADD CONSTRAINT FK_6A2F2F95DB805178 FOREIGN KEY (quote_id) REFERENCES quotes (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE invoices ADD CONSTRAINT FK_6A2F2F959F85F85C FOREIGN KEY (recurring_invoice_id) REFERENCES recurring_invoices (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE invoice_contact ADD CONSTRAINT FK_BEBBD0EB2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice_contact ADD CONSTRAINT FK_BEBBD0EBE7A1254A FOREIGN KEY (contact_id) REFERENCES contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE line_tax ADD CONSTRAINT FK_7DCA892CB2A824D8 FOREIGN KEY (tax_id) REFERENCES tax_rates (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE line_tax ADD CONSTRAINT FK_7DCA892CBFA24391 FOREIGN KEY (invoice_line_id) REFERENCES invoice_lines (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE line_tax ADD CONSTRAINT FK_7DCA892CA294DDC6 FOREIGN KEY (quote_line_id) REFERENCES quote_lines (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE line_tax ADD CONSTRAINT FK_7DCA892C979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mcp_access_token ADD CONSTRAINT FK_8611E11719EB6921 FOREIGN KEY (client_id) REFERENCES mcp_oauth_client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mcp_access_token ADD CONSTRAINT FK_8611E117A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mcp_access_token ADD CONSTRAINT FK_8611E117979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mcp_consent_grant ADD CONSTRAINT FK_90F67619EB6921 FOREIGN KEY (client_id) REFERENCES mcp_oauth_client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mcp_consent_grant ADD CONSTRAINT FK_90F676A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mcp_consent_grant ADD CONSTRAINT FK_90F676979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mcp_oauth_auth_code ADD CONSTRAINT FK_3324447419EB6921 FOREIGN KEY (client_id) REFERENCES mcp_oauth_client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mcp_oauth_auth_code ADD CONSTRAINT FK_33244474A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mcp_oauth_auth_code ADD CONSTRAINT FK_33244474979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mcp_oauth_client ADD CONSTRAINT FK_9DC01B32B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE mcp_refresh_token ADD CONSTRAINT FK_7C5FE042CCB2688 FOREIGN KEY (access_token_id) REFERENCES mcp_access_token (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification_transport_setting ADD CONSTRAINT FK_C825F288A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE notification_transport_setting ADD CONSTRAINT FK_C825F288979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification_user_setting ADD CONSTRAINT FK_C6774CA7A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE notification_user_setting ADD CONSTRAINT FK_C6774CA7979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE usernotification_transportsetting ADD CONSTRAINT FK_F4035D6F58E61F52 FOREIGN KEY (usernotification_id) REFERENCES notification_user_setting (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE usernotification_transportsetting ADD CONSTRAINT FK_F4035D6F356A9AF4 FOREIGN KEY (transportsetting_id) REFERENCES notification_transport_setting (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment_methods ADD CONSTRAINT FK_4FABF983979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B322989F1FD FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B32C7440455 FOREIGN KEY (client) REFERENCES clients (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B3219883967 FOREIGN KEY (method_id) REFERENCES payment_methods (id)');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B32979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quote_lines ADD CONSTRAINT FK_42FE01F7DB805178 FOREIGN KEY (quote_id) REFERENCES quotes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quote_lines ADD CONSTRAINT FK_42FE01F7979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quotes ADD CONSTRAINT FK_A1B588C519EB6921 FOREIGN KEY (client_id) REFERENCES clients (id)');
        $this->addSql('ALTER TABLE quotes ADD CONSTRAINT FK_A1B588C5979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quote_contact ADD CONSTRAINT FK_A38D4EBCDB805178 FOREIGN KEY (quote_id) REFERENCES quotes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quote_contact ADD CONSTRAINT FK_A38D4EBCE7A1254A FOREIGN KEY (contact_id) REFERENCES contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE recurring_invoices ADD CONSTRAINT FK_FE93E284979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE recurring_invoices ADD CONSTRAINT FK_FE93E28419EB6921 FOREIGN KEY (client_id) REFERENCES clients (id)');
        $this->addSql('ALTER TABLE recurringinvoice_contacts ADD CONSTRAINT FK_DA79A131E31CCDF FOREIGN KEY (recurringinvoice_id) REFERENCES recurring_invoices (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE recurringinvoice_contacts ADD CONSTRAINT FK_DA79A131E7A1254A FOREIGN KEY (contact_id) REFERENCES contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE recurring_options ADD CONSTRAINT FK_8C36F0E416CCF0F FOREIGN KEY (recurringInvoice_id) REFERENCES recurring_invoices (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE security_token ADD CONSTRAINT FK_B38B42914C3A3BB FOREIGN KEY (payment_id) REFERENCES payments (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tax_identifier ADD CONSTRAINT FK_ACB973B619EB6921 FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tax_identifier ADD CONSTRAINT FK_ACB973B6979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tax_rates ADD CONSTRAINT FK_F7AE5E1D979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_invitations ADD CONSTRAINT FK_8A3CD93BA7B4A7E3 FOREIGN KEY (invited_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE user_invitations ADD CONSTRAINT FK_8A3CD93B979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_settings ADD CONSTRAINT FK_5C844C5A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE user_company ADD CONSTRAINT FK_17B21745A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_company ADD CONSTRAINT FK_17B21745979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE addresses DROP FOREIGN KEY FK_6FCA751619EB6921');
        $this->addSql('ALTER TABLE addresses DROP FOREIGN KEY FK_6FCA7516979B1AD6');
        $this->addSql('ALTER TABLE api_token_history DROP FOREIGN KEY FK_61D8DC4441DEE7B9');
        $this->addSql('ALTER TABLE api_token_history DROP FOREIGN KEY FK_61D8DC44979B1AD6');
        $this->addSql('ALTER TABLE api_tokens DROP FOREIGN KEY FK_2CAD560EA76ED395');
        $this->addSql('ALTER TABLE api_tokens DROP FOREIGN KEY FK_2CAD560E979B1AD6');
        $this->addSql('ALTER TABLE app_config DROP FOREIGN KEY FK_318942FC979B1AD6');
        $this->addSql('ALTER TABLE client_credit DROP FOREIGN KEY FK_4967254D19EB6921');
        $this->addSql('ALTER TABLE client_credit DROP FOREIGN KEY FK_4967254D979B1AD6');
        $this->addSql('ALTER TABLE clients DROP FOREIGN KEY FK_C82E74979B1AD6');
        $this->addSql('ALTER TABLE contacts DROP FOREIGN KEY FK_3340157319EB6921');
        $this->addSql('ALTER TABLE contacts DROP FOREIGN KEY FK_33401573979B1AD6');
        $this->addSql('ALTER TABLE custom_field DROP FOREIGN KEY FK_98F8BD31979B1AD6');
        $this->addSql('ALTER TABLE custom_field_value DROP FOREIGN KEY FK_EC7B05443707B0');
        $this->addSql('ALTER TABLE custom_field_value DROP FOREIGN KEY FK_EC7B05979B1AD6');
        $this->addSql('ALTER TABLE export_jobs DROP FOREIGN KEY FK_8E225B2E979B1AD6');
        $this->addSql('ALTER TABLE invoice_lines DROP FOREIGN KEY FK_72DBDC232989F1FD');
        $this->addSql('ALTER TABLE invoice_lines DROP FOREIGN KEY FK_72DBDC23979B1AD6');
        $this->addSql('ALTER TABLE invoice_lines DROP FOREIGN KEY FK_72DBDC23416CCF0F');
        $this->addSql('ALTER TABLE invoice_reminders DROP FOREIGN KEY FK_83D48482989F1FD');
        $this->addSql('ALTER TABLE invoice_reminders DROP FOREIGN KEY FK_83D4848979B1AD6');
        $this->addSql('ALTER TABLE invoice_tax DROP FOREIGN KEY FK_2670D5B5B2A824D8');
        $this->addSql('ALTER TABLE invoice_tax DROP FOREIGN KEY FK_2670D5B52989F1FD');
        $this->addSql('ALTER TABLE invoice_tax DROP FOREIGN KEY FK_2670D5B5DB805178');
        $this->addSql('ALTER TABLE invoice_tax DROP FOREIGN KEY FK_2670D5B59F85F85C');
        $this->addSql('ALTER TABLE invoice_tax DROP FOREIGN KEY FK_2670D5B5979B1AD6');
        $this->addSql('ALTER TABLE invoices DROP FOREIGN KEY FK_6A2F2F95979B1AD6');
        $this->addSql('ALTER TABLE invoices DROP FOREIGN KEY FK_6A2F2F9519EB6921');
        $this->addSql('ALTER TABLE invoices DROP FOREIGN KEY FK_6A2F2F95DB805178');
        $this->addSql('ALTER TABLE invoices DROP FOREIGN KEY FK_6A2F2F959F85F85C');
        $this->addSql('ALTER TABLE invoice_contact DROP FOREIGN KEY FK_BEBBD0EB2989F1FD');
        $this->addSql('ALTER TABLE invoice_contact DROP FOREIGN KEY FK_BEBBD0EBE7A1254A');
        $this->addSql('ALTER TABLE line_tax DROP FOREIGN KEY FK_7DCA892CB2A824D8');
        $this->addSql('ALTER TABLE line_tax DROP FOREIGN KEY FK_7DCA892CBFA24391');
        $this->addSql('ALTER TABLE line_tax DROP FOREIGN KEY FK_7DCA892CA294DDC6');
        $this->addSql('ALTER TABLE line_tax DROP FOREIGN KEY FK_7DCA892C979B1AD6');
        $this->addSql('ALTER TABLE mcp_access_token DROP FOREIGN KEY FK_8611E11719EB6921');
        $this->addSql('ALTER TABLE mcp_access_token DROP FOREIGN KEY FK_8611E117A76ED395');
        $this->addSql('ALTER TABLE mcp_access_token DROP FOREIGN KEY FK_8611E117979B1AD6');
        $this->addSql('ALTER TABLE mcp_consent_grant DROP FOREIGN KEY FK_90F67619EB6921');
        $this->addSql('ALTER TABLE mcp_consent_grant DROP FOREIGN KEY FK_90F676A76ED395');
        $this->addSql('ALTER TABLE mcp_consent_grant DROP FOREIGN KEY FK_90F676979B1AD6');
        $this->addSql('ALTER TABLE mcp_oauth_auth_code DROP FOREIGN KEY FK_3324447419EB6921');
        $this->addSql('ALTER TABLE mcp_oauth_auth_code DROP FOREIGN KEY FK_33244474A76ED395');
        $this->addSql('ALTER TABLE mcp_oauth_auth_code DROP FOREIGN KEY FK_33244474979B1AD6');
        $this->addSql('ALTER TABLE mcp_oauth_client DROP FOREIGN KEY FK_9DC01B32B03A8386');
        $this->addSql('ALTER TABLE mcp_refresh_token DROP FOREIGN KEY FK_7C5FE042CCB2688');
        $this->addSql('ALTER TABLE notification_transport_setting DROP FOREIGN KEY FK_C825F288A76ED395');
        $this->addSql('ALTER TABLE notification_transport_setting DROP FOREIGN KEY FK_C825F288979B1AD6');
        $this->addSql('ALTER TABLE notification_user_setting DROP FOREIGN KEY FK_C6774CA7A76ED395');
        $this->addSql('ALTER TABLE notification_user_setting DROP FOREIGN KEY FK_C6774CA7979B1AD6');
        $this->addSql('ALTER TABLE usernotification_transportsetting DROP FOREIGN KEY FK_F4035D6F58E61F52');
        $this->addSql('ALTER TABLE usernotification_transportsetting DROP FOREIGN KEY FK_F4035D6F356A9AF4');
        $this->addSql('ALTER TABLE payment_methods DROP FOREIGN KEY FK_4FABF983979B1AD6');
        $this->addSql('ALTER TABLE payments DROP FOREIGN KEY FK_65D29B322989F1FD');
        $this->addSql('ALTER TABLE payments DROP FOREIGN KEY FK_65D29B32C7440455');
        $this->addSql('ALTER TABLE payments DROP FOREIGN KEY FK_65D29B3219883967');
        $this->addSql('ALTER TABLE payments DROP FOREIGN KEY FK_65D29B32979B1AD6');
        $this->addSql('ALTER TABLE quote_lines DROP FOREIGN KEY FK_42FE01F7DB805178');
        $this->addSql('ALTER TABLE quote_lines DROP FOREIGN KEY FK_42FE01F7979B1AD6');
        $this->addSql('ALTER TABLE quotes DROP FOREIGN KEY FK_A1B588C519EB6921');
        $this->addSql('ALTER TABLE quotes DROP FOREIGN KEY FK_A1B588C5979B1AD6');
        $this->addSql('ALTER TABLE quote_contact DROP FOREIGN KEY FK_A38D4EBCDB805178');
        $this->addSql('ALTER TABLE quote_contact DROP FOREIGN KEY FK_A38D4EBCE7A1254A');
        $this->addSql('ALTER TABLE recurring_invoices DROP FOREIGN KEY FK_FE93E284979B1AD6');
        $this->addSql('ALTER TABLE recurring_invoices DROP FOREIGN KEY FK_FE93E28419EB6921');
        $this->addSql('ALTER TABLE recurringinvoice_contacts DROP FOREIGN KEY FK_DA79A131E31CCDF');
        $this->addSql('ALTER TABLE recurringinvoice_contacts DROP FOREIGN KEY FK_DA79A131E7A1254A');
        $this->addSql('ALTER TABLE recurring_options DROP FOREIGN KEY FK_8C36F0E416CCF0F');
        $this->addSql('ALTER TABLE reset_password_request DROP FOREIGN KEY FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE security_token DROP FOREIGN KEY FK_B38B42914C3A3BB');
        $this->addSql('ALTER TABLE tax_identifier DROP FOREIGN KEY FK_ACB973B619EB6921');
        $this->addSql('ALTER TABLE tax_identifier DROP FOREIGN KEY FK_ACB973B6979B1AD6');
        $this->addSql('ALTER TABLE tax_rates DROP FOREIGN KEY FK_F7AE5E1D979B1AD6');
        $this->addSql('ALTER TABLE user_invitations DROP FOREIGN KEY FK_8A3CD93BA7B4A7E3');
        $this->addSql('ALTER TABLE user_invitations DROP FOREIGN KEY FK_8A3CD93B979B1AD6');
        $this->addSql('ALTER TABLE user_settings DROP FOREIGN KEY FK_5C844C5A76ED395');
        $this->addSql('ALTER TABLE user_company DROP FOREIGN KEY FK_17B21745A76ED395');
        $this->addSql('ALTER TABLE user_company DROP FOREIGN KEY FK_17B21745979B1AD6');
        $this->addSql('DROP TABLE addresses');
        $this->addSql('DROP TABLE api_token_history');
        $this->addSql('DROP TABLE api_tokens');
        $this->addSql('DROP TABLE app_config');
        $this->addSql('DROP TABLE client_credit');
        $this->addSql('DROP TABLE clients');
        $this->addSql('DROP TABLE companies');
        $this->addSql('DROP TABLE contacts');
        $this->addSql('DROP TABLE custom_field');
        $this->addSql('DROP TABLE custom_field_value');
        $this->addSql('DROP TABLE export_jobs');
        $this->addSql('DROP TABLE invoice_lines');
        $this->addSql('DROP TABLE invoice_reminders');
        $this->addSql('DROP TABLE invoice_tax');
        $this->addSql('DROP TABLE invoices');
        $this->addSql('DROP TABLE invoice_contact');
        $this->addSql('DROP TABLE line_tax');
        $this->addSql('DROP TABLE mcp_access_token');
        $this->addSql('DROP TABLE mcp_consent_grant');
        $this->addSql('DROP TABLE mcp_oauth_auth_code');
        $this->addSql('DROP TABLE mcp_oauth_client');
        $this->addSql('DROP TABLE mcp_refresh_token');
        $this->addSql('DROP TABLE notification_transport_setting');
        $this->addSql('DROP TABLE notification_user_setting');
        $this->addSql('DROP TABLE usernotification_transportsetting');
        $this->addSql('DROP TABLE payment_methods');
        $this->addSql('DROP TABLE payments');
        $this->addSql('DROP TABLE quote_lines');
        $this->addSql('DROP TABLE quotes');
        $this->addSql('DROP TABLE quote_contact');
        $this->addSql('DROP TABLE recurring_invoices');
        $this->addSql('DROP TABLE recurringinvoice_contacts');
        $this->addSql('DROP TABLE recurring_options');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE security_token');
        $this->addSql('DROP TABLE tax_identifier');
        $this->addSql('DROP TABLE tax_rates');
        $this->addSql('DROP TABLE user_invitations');
        $this->addSql('DROP TABLE user_settings');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE user_company');
        $this->addSql('DROP TABLE version');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
