<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adds the SaaS bundle's database schema (saas_plan, saas_plan_feature,
 * webhook_event_log, saas_subscription, saas_subscription_log, saas_trial)
 * that was missing from the baseline migration because it was generated
 * while SOLIDINVOICE_PLATFORM=saas was not enabled.
 *
 * This migration is purely additive: it only creates new tables, indexes
 * and foreign keys. It never touches any pre-existing table (users,
 * companies, clients, invoices, quotes, payments, etc.) and contains no
 * DROP, TRUNCATE, or destructive rename of any kind.
 *
 * Schema was hand-derived from the vendor SaaS entity metadata
 * (vendor/solidworx/platform/src/Bundle/Saas/Entity/*.php) and cross
 * -checked against the column/index/FK conventions already used in
 * migrations/Version20260927020255.php (Ulid BINARY(16) PKs/FKs, native
 * JSON columns, LONGTEXT for TEXT fields, DC2Type comments, FK constraints
 * as separate ALTER TABLE statements). It was not generated by running
 * doctrine:migrations:diff (PHP/Doctrine tooling was not available in the
 * environment that authored this file) — please cross-check it yourself
 * with `SOLIDINVOICE_PLATFORM=saas php bin/console doctrine:migrations:diff --formatted`
 * before applying, per the accompanying report.
 */
final class Version20260927163300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add missing SaaS bundle schema (saas_plan, saas_plan_feature, webhook_event_log, saas_subscription, saas_subscription_log, saas_trial) — additive only, no changes to existing tables or data.';
    }

    public function up(Schema $schema): void
    {
        // --- CREATE TABLE, in FK-dependency order -------------------------------------------------

        $this->addSql('CREATE TABLE saas_plan (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', name VARCHAR(255) NOT NULL, planId VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, price INT NOT NULL, trialDuration VARCHAR(255) DEFAULT NULL COMMENT \'(DC2Type:dateinterval)\', `default` TINYINT(1) DEFAULT 0 NOT NULL, active TINYINT(1) DEFAULT 1 NOT NULL, UNIQUE INDEX UNIQ_SAAS_PLAN_PLAN_ID (planId), INDEX IDX_SAAS_PLAN_PLAN_ID (planId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE saas_plan_feature (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', plan_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', feature_key VARCHAR(100) NOT NULL, type VARCHAR(20) NOT NULL, value JSON NOT NULL, description LONGTEXT DEFAULT NULL, INDEX IDX_SAAS_PLAN_FEATURE_PLAN (plan_id), INDEX IDX_SAAS_PLAN_FEATURE_FEATURE_KEY (feature_key), UNIQUE INDEX plan_feature_unique (plan_id, feature_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE webhook_event_log (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', gateway VARCHAR(50) NOT NULL, event_type VARCHAR(100) DEFAULT NULL, status VARCHAR(20) NOT NULL, payload JSON NOT NULL, request_headers JSON NOT NULL, gateway_event_id VARCHAR(128) DEFAULT NULL, external_subscription_id VARCHAR(128) DEFAULT NULL, received_at DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz_immutable)\', processed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz_immutable)\', error_message LONGTEXT DEFAULT NULL, INDEX idx_webhook_event_log_gateway (gateway), INDEX idx_webhook_event_log_gateway_event_type (gateway, event_type), INDEX idx_webhook_event_log_status (status), INDEX idx_webhook_event_log_gateway_event_id (gateway_event_id), INDEX idx_webhook_event_log_external_subscription_id (external_subscription_id), INDEX idx_webhook_event_log_received_at (received_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE saas_subscription (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', startDate DATETIME(3) NOT NULL COMMENT \'(DC2Type:datetimetz_immutable)\', endDate DATETIME(3) NOT NULL COMMENT \'(DC2Type:datetimetz_immutable)\', subscriber_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', plan_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', status VARCHAR(45) NOT NULL, subscriptionId VARCHAR(255) DEFAULT NULL, pending_plan_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', pending_plan_change_at DATETIME(3) DEFAULT NULL COMMENT \'(DC2Type:datetimetz_immutable)\', INDEX IDX_SAAS_SUBSCRIPTION_STATUS (status), UNIQUE INDEX UNIQ_SAAS_SUBSCRIPTION_SUBSCRIPTION_ID (subscriptionId), INDEX IDX_SAAS_SUBSCRIPTION_SUBSCRIPTION_ID (subscriptionId), INDEX IDX_SAAS_SUBSCRIPTION_SUBSCRIBER (subscriber_id), INDEX IDX_SAAS_SUBSCRIPTION_PLAN (plan_id), INDEX IDX_SAAS_SUBSCRIPTION_PENDING_PLAN (pending_plan_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE saas_subscription_log (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', created_at DATETIME(3) NOT NULL COMMENT \'(DC2Type:datetimetz_immutable)\', subscription_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', type VARCHAR(45) NOT NULL, comment VARCHAR(255) DEFAULT NULL, webhook_event_log_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:ulid)\', metadata JSON DEFAULT NULL, INDEX IDX_SAAS_SUBSCRIPTION_LOG_TYPE (type), INDEX idx_subscription_log_subscription_created (subscription_id, created_at), INDEX IDX_SAAS_SUBSCRIPTION_LOG_WEBHOOK_EVENT (webhook_event_log_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE saas_trial (id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', createdAt DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', subscription_id BINARY(16) NOT NULL COMMENT \'(DC2Type:ulid)\', UNIQUE INDEX UNIQ_SAAS_TRIAL_USER (user_id), UNIQUE INDEX UNIQ_SAAS_TRIAL_SUBSCRIPTION (subscription_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        // --- Foreign keys, added after all tables exist -------------------------------------------

        $this->addSql('ALTER TABLE saas_plan_feature ADD CONSTRAINT FK_SAAS_PLAN_FEATURE_PLAN FOREIGN KEY (plan_id) REFERENCES saas_plan (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE saas_subscription ADD CONSTRAINT FK_SAAS_SUBSCRIPTION_SUBSCRIBER FOREIGN KEY (subscriber_id) REFERENCES companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE saas_subscription ADD CONSTRAINT FK_SAAS_SUBSCRIPTION_PLAN FOREIGN KEY (plan_id) REFERENCES saas_plan (id)');
        $this->addSql('ALTER TABLE saas_subscription ADD CONSTRAINT FK_SAAS_SUBSCRIPTION_PENDING_PLAN FOREIGN KEY (pending_plan_id) REFERENCES saas_plan (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE saas_subscription_log ADD CONSTRAINT FK_SAAS_SUBSCRIPTION_LOG_SUBSCRIPTION FOREIGN KEY (subscription_id) REFERENCES saas_subscription (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE saas_subscription_log ADD CONSTRAINT FK_SAAS_SUBSCRIPTION_LOG_WEBHOOK_EVENT FOREIGN KEY (webhook_event_log_id) REFERENCES webhook_event_log (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE saas_trial ADD CONSTRAINT FK_SAAS_TRIAL_USER FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE saas_trial ADD CONSTRAINT FK_SAAS_TRIAL_SUBSCRIPTION FOREIGN KEY (subscription_id) REFERENCES saas_subscription (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // Reverse order: drop foreign keys first, then tables in reverse
        // dependency order. This never touches any table that existed
        // before this migration.

        $this->addSql('ALTER TABLE saas_trial DROP FOREIGN KEY FK_SAAS_TRIAL_SUBSCRIPTION');
        $this->addSql('ALTER TABLE saas_trial DROP FOREIGN KEY FK_SAAS_TRIAL_USER');
        $this->addSql('ALTER TABLE saas_subscription_log DROP FOREIGN KEY FK_SAAS_SUBSCRIPTION_LOG_WEBHOOK_EVENT');
        $this->addSql('ALTER TABLE saas_subscription_log DROP FOREIGN KEY FK_SAAS_SUBSCRIPTION_LOG_SUBSCRIPTION');
        $this->addSql('ALTER TABLE saas_subscription DROP FOREIGN KEY FK_SAAS_SUBSCRIPTION_PENDING_PLAN');
        $this->addSql('ALTER TABLE saas_subscription DROP FOREIGN KEY FK_SAAS_SUBSCRIPTION_PLAN');
        $this->addSql('ALTER TABLE saas_subscription DROP FOREIGN KEY FK_SAAS_SUBSCRIPTION_SUBSCRIBER');
        $this->addSql('ALTER TABLE saas_plan_feature DROP FOREIGN KEY FK_SAAS_PLAN_FEATURE_PLAN');

        $this->addSql('DROP TABLE saas_trial');
        $this->addSql('DROP TABLE saas_subscription_log');
        $this->addSql('DROP TABLE saas_subscription');
        $this->addSql('DROP TABLE webhook_event_log');
        $this->addSql('DROP TABLE saas_plan_feature');
        $this->addSql('DROP TABLE saas_plan');
    }
}
